
esp_toml_version = 1.0

firmware_images_url = "https://nollstead.github.io/BTAudio/webflash/"
supported_apps = ["BTAudio"]

[BTAudio]
chipsets = ["ESP32"]
image.esp32 = "BTAudio.bin"

description = "Nollstead Studio BT Audio Firmware â€“ Version 0.0.1"

# Full Markdown goes here
readme.text = "https://nollstead.github.io/BTAudio/app-info.md"
