title = "Nollstead Studio BTAudio"
schema = 1

# --- Version 0.0.1 ---
[[apps]]
name = "BTAudio 0.0.1"
chipsets = ["ESP32"]
version = "0.0.1"
date = "2026-01-16"
label = "latest update"

  [[apps.binaries]]
  address = "0x000000"
  path = "https://nollstead.github.io/BTAudio/webflash/BTAudio.bin"

# --- Version 0.0.0 ---
[[apps]]
name = "BTAudio 0.0.0"
chipsets = ["ESP32"]
version = "0.0.0"
date = "2026-01-15"
label = "Base Version"

  [[apps.binaries]]
  address = "0x000000"
  path = "https://nollstead.github.io/BTAudio/webflash/BTAudio.bin"
